import 'models.dart';

/// Explicit scenario data used by the campaign and player-level screens.
///
/// Keeping the values here makes a level a real, inspectable scenario rather
/// than a UI tile whose configuration is calculated from its number.
class CampaignScenario {
  const CampaignScenario({
    required this.level,
    required this.title,
    required this.mapSize,
    required this.players,
    required this.seed,
    required this.difficulty,
    required this.trees,
    this.startingProvinces = 0,
    this.fog = false,
    this.diplomacy = false,
    this.slay = false,
  });

  final int level;
  final String title;
  final MapSize mapSize;
  final int players;
  final int seed;
  final AiDifficulty difficulty;
  final int trees;
  final int startingProvinces;
  final bool fog;
  final bool diplomacy;
  final bool slay;

  GameConfig toConfig() => GameConfig(
    mapSize: mapSize,
    playerCount: players,
    humanCount: 1,
    seed: seed,
    difficulty: difficulty,
    treePercent: trees,
    startingProvinceCount: startingProvinces,
    slayRules: slay,
    fogOfWar: fog,
    diplomacy: diplomacy,
    campaignLevel: level,
  );
}

class PlayerScenario {
  const PlayerScenario({
    required this.name,
    required this.author,
    required this.mapSize,
    required this.players,
    required this.seed,
    required this.difficulty,
    required this.trees,
    this.humans = 1,
    this.startingProvinces = 0,
    this.historical = false,
    this.multiplayer = false,
    this.diplomacy = false,
    this.fog = false,
    this.slay = false,
  });

  final String name;
  final String author;
  final MapSize mapSize;
  final int players;
  final int humans;
  final int seed;
  final AiDifficulty difficulty;
  final int trees;
  final int startingProvinces;
  final bool historical;
  final bool multiplayer;
  final bool diplomacy;
  final bool fog;
  final bool slay;

  GameConfig toConfig() => GameConfig(
    mapSize: mapSize,
    playerCount: players,
    humanCount: humans,
    seed: seed,
    difficulty: difficulty,
    treePercent: trees,
    startingProvinceCount: startingProvinces,
    slayRules: slay,
    fogOfWar: fog,
    diplomacy: diplomacy,
  );
}

/// Fifty hand-curated, fixed-seed procedural campaign presets.
///
/// These are reproducible configurations, not copies of Antiyoy's authored
/// level geometry. Exact user-supplied Antiyoy HD level codes are handled by
/// `AntiyoyHdLevelImporter` at the editor import boundary.
const campaignScenarios = <CampaignScenario>[
  CampaignScenario(
    level: 1,
    title: 'Алғашқы шекара',
    mapSize: MapSize.small,
    players: 2,
    seed: 11417,
    difficulty: AiDifficulty.veryEasy,
    trees: 5,
    startingProvinces: 1,
  ),
  CampaignScenario(
    level: 2,
    title: 'Екі қала',
    mapSize: MapSize.small,
    players: 2,
    seed: 22853,
    difficulty: AiDifficulty.veryEasy,
    trees: 10,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 3,
    title: 'Үш бағыт',
    mapSize: MapSize.small,
    players: 3,
    seed: 34781,
    difficulty: AiDifficulty.veryEasy,
    trees: 15,
    startingProvinces: 1,
  ),
  CampaignScenario(
    level: 4,
    title: 'Орман жолы',
    mapSize: MapSize.small,
    players: 3,
    seed: 46133,
    difficulty: AiDifficulty.easy,
    trees: 30,
  ),
  CampaignScenario(
    level: 5,
    title: 'Қамал сабағы',
    mapSize: MapSize.small,
    players: 3,
    seed: 57991,
    difficulty: AiDifficulty.easy,
    trees: 10,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 6,
    title: 'Төрт түс',
    mapSize: MapSize.small,
    players: 4,
    seed: 69127,
    difficulty: AiDifficulty.easy,
    trees: 15,
  ),
  CampaignScenario(
    level: 7,
    title: 'Тар өткел',
    mapSize: MapSize.small,
    players: 4,
    seed: 80701,
    difficulty: AiDifficulty.easy,
    trees: 20,
    fog: true,
  ),
  CampaignScenario(
    level: 8,
    title: 'Бірінші арал',
    mapSize: MapSize.small,
    players: 4,
    seed: 92363,
    difficulty: AiDifficulty.easy,
    trees: 15,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 9,
    title: 'Теңгерім',
    mapSize: MapSize.medium,
    players: 4,
    seed: 103979,
    difficulty: AiDifficulty.normal,
    trees: 10,
  ),
  CampaignScenario(
    level: 10,
    title: 'Көрінбейтін шекара',
    mapSize: MapSize.medium,
    players: 4,
    seed: 115727,
    difficulty: AiDifficulty.normal,
    trees: 15,
    fog: true,
  ),
  CampaignScenario(
    level: 11,
    title: 'Бес мемлекет',
    mapSize: MapSize.medium,
    players: 5,
    seed: 127453,
    difficulty: AiDifficulty.normal,
    trees: 10,
  ),
  CampaignScenario(
    level: 12,
    title: 'Екі майдан',
    mapSize: MapSize.medium,
    players: 5,
    seed: 139201,
    difficulty: AiDifficulty.normal,
    trees: 20,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 13,
    title: 'Порттар жарысы',
    mapSize: MapSize.medium,
    players: 5,
    seed: 151007,
    difficulty: AiDifficulty.normal,
    trees: 5,
  ),
  CampaignScenario(
    level: 14,
    title: 'Тұманды теңіз',
    mapSize: MapSize.medium,
    players: 5,
    seed: 162749,
    difficulty: AiDifficulty.normal,
    trees: 15,
    fog: true,
  ),
  CampaignScenario(
    level: 15,
    title: 'Алты тақ',
    mapSize: MapSize.medium,
    players: 6,
    seed: 174467,
    difficulty: AiDifficulty.hard,
    trees: 10,
  ),
  CampaignScenario(
    level: 16,
    title: 'Алғашқы келісім',
    mapSize: MapSize.medium,
    players: 5,
    seed: 186239,
    difficulty: AiDifficulty.hard,
    trees: 15,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 17,
    title: 'Сенім бағасы',
    mapSize: MapSize.medium,
    players: 6,
    seed: 198013,
    difficulty: AiDifficulty.hard,
    trees: 20,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 18,
    title: 'Slay шекарасы',
    mapSize: MapSize.medium,
    players: 6,
    seed: 209771,
    difficulty: AiDifficulty.normal,
    trees: 5,
    slay: true,
  ),
  CampaignScenario(
    level: 19,
    title: 'Бөлінген патшалық',
    mapSize: MapSize.medium,
    players: 6,
    seed: 221537,
    difficulty: AiDifficulty.hard,
    trees: 15,
    startingProvinces: 3,
  ),
  CampaignScenario(
    level: 20,
    title: 'Қара белгі',
    mapSize: MapSize.medium,
    players: 6,
    seed: 233287,
    difficulty: AiDifficulty.hard,
    trees: 20,
    fog: true,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 21,
    title: 'Жеті жағалау',
    mapSize: MapSize.large,
    players: 7,
    seed: 245071,
    difficulty: AiDifficulty.hard,
    trees: 10,
  ),
  CampaignScenario(
    level: 22,
    title: 'Артиллерия үні',
    mapSize: MapSize.large,
    players: 6,
    seed: 256867,
    difficulty: AiDifficulty.hard,
    trees: 15,
  ),
  CampaignScenario(
    level: 23,
    title: 'Ұзақ бітім',
    mapSize: MapSize.large,
    players: 7,
    seed: 268657,
    difficulty: AiDifficulty.hard,
    trees: 20,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 24,
    title: 'Түнгі десант',
    mapSize: MapSize.large,
    players: 7,
    seed: 280463,
    difficulty: AiDifficulty.hard,
    trees: 10,
    fog: true,
  ),
  CampaignScenario(
    level: 25,
    title: 'Сегіз держава',
    mapSize: MapSize.large,
    players: 8,
    seed: 292273,
    difficulty: AiDifficulty.veryHard,
    trees: 15,
  ),
  CampaignScenario(
    level: 26,
    title: 'Қымбат флот',
    mapSize: MapSize.large,
    players: 7,
    seed: 304081,
    difficulty: AiDifficulty.veryHard,
    trees: 10,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 27,
    title: 'Достар мен жаулар',
    mapSize: MapSize.large,
    players: 8,
    seed: 315883,
    difficulty: AiDifficulty.veryHard,
    trees: 15,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 28,
    title: 'Сұр әлем',
    mapSize: MapSize.large,
    players: 8,
    seed: 327689,
    difficulty: AiDifficulty.veryHard,
    trees: 20,
    fog: true,
  ),
  CampaignScenario(
    level: 29,
    title: 'Slay құрлығы',
    mapSize: MapSize.large,
    players: 8,
    seed: 339491,
    difficulty: AiDifficulty.hard,
    trees: 5,
    slay: true,
  ),
  CampaignScenario(
    level: 30,
    title: 'Үш астана',
    mapSize: MapSize.large,
    players: 8,
    seed: 351287,
    difficulty: AiDifficulty.veryHard,
    trees: 15,
    startingProvinces: 3,
  ),
  CampaignScenario(
    level: 31,
    title: 'Тоғыз түс',
    mapSize: MapSize.large,
    players: 9,
    seed: 363067,
    difficulty: AiDifficulty.veryHard,
    trees: 10,
  ),
  CampaignScenario(
    level: 32,
    title: 'Шеберге қадам',
    mapSize: MapSize.large,
    players: 8,
    seed: 374837,
    difficulty: AiDifficulty.master,
    trees: 15,
  ),
  CampaignScenario(
    level: 33,
    title: 'Теңіз қорғаны',
    mapSize: MapSize.large,
    players: 9,
    seed: 386603,
    difficulty: AiDifficulty.master,
    trees: 10,
    fog: true,
  ),
  CampaignScenario(
    level: 34,
    title: 'Қарыздар соғысы',
    mapSize: MapSize.large,
    players: 9,
    seed: 398369,
    difficulty: AiDifficulty.master,
    trees: 20,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 35,
    title: 'Он мемлекет',
    mapSize: MapSize.huge,
    players: 10,
    seed: 410117,
    difficulty: AiDifficulty.veryHard,
    trees: 15,
  ),
  CampaignScenario(
    level: 36,
    title: 'Қос ереже',
    mapSize: MapSize.huge,
    players: 10,
    seed: 421859,
    difficulty: AiDifficulty.master,
    trees: 5,
    slay: true,
    fog: true,
  ),
  CampaignScenario(
    level: 37,
    title: 'Теңіз империялары',
    mapSize: MapSize.huge,
    players: 10,
    seed: 433601,
    difficulty: AiDifficulty.master,
    trees: 10,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 38,
    title: 'Жасырын одақ',
    mapSize: MapSize.huge,
    players: 10,
    seed: 445337,
    difficulty: AiDifficulty.master,
    trees: 20,
    fog: true,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 39,
    title: 'Он бір тәж',
    mapSize: MapSize.huge,
    players: 11,
    seed: 457069,
    difficulty: AiDifficulty.master,
    trees: 15,
  ),
  CampaignScenario(
    level: 40,
    title: 'Үш провинция',
    mapSize: MapSize.huge,
    players: 10,
    seed: 468799,
    difficulty: AiDifficulty.master,
    trees: 10,
    startingProvinces: 3,
  ),
  CampaignScenario(
    level: 41,
    title: 'Үлкен Slay',
    mapSize: MapSize.huge,
    players: 11,
    seed: 480533,
    difficulty: AiDifficulty.veryHard,
    trees: 5,
    slay: true,
  ),
  CampaignScenario(
    level: 42,
    title: 'Тұман кеңесі',
    mapSize: MapSize.huge,
    players: 11,
    seed: 492259,
    difficulty: AiDifficulty.master,
    trees: 20,
    fog: true,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 43,
    title: 'Он екі түс',
    mapSize: MapSize.huge,
    players: 12,
    seed: 503983,
    difficulty: AiDifficulty.master,
    trees: 15,
  ),
  CampaignScenario(
    level: 44,
    title: 'Аралдар келісімі',
    mapSize: MapSize.huge,
    players: 12,
    seed: 515711,
    difficulty: AiDifficulty.master,
    trees: 10,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 45,
    title: 'Қара теңіз',
    mapSize: MapSize.huge,
    players: 12,
    seed: 527441,
    difficulty: AiDifficulty.master,
    trees: 20,
    fog: true,
  ),
  CampaignScenario(
    level: 46,
    title: 'Он үш ту',
    mapSize: MapSize.huge,
    players: 13,
    seed: 539171,
    difficulty: AiDifficulty.master,
    trees: 10,
    startingProvinces: 2,
  ),
  CampaignScenario(
    level: 47,
    title: 'Соңғы одақ',
    mapSize: MapSize.huge,
    players: 13,
    seed: 550903,
    difficulty: AiDifficulty.master,
    trees: 20,
    fog: true,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 48,
    title: 'Он төрт шекара',
    mapSize: MapSize.huge,
    players: 14,
    seed: 562621,
    difficulty: AiDifficulty.master,
    trees: 15,
    slay: true,
  ),
  CampaignScenario(
    level: 49,
    title: 'Барлық жүйе',
    mapSize: MapSize.huge,
    players: 15,
    seed: 574357,
    difficulty: AiDifficulty.master,
    trees: 20,
    startingProvinces: 3,
    fog: true,
    diplomacy: true,
  ),
  CampaignScenario(
    level: 50,
    title: 'Он бес империя',
    mapSize: MapSize.huge,
    players: 15,
    seed: 586081,
    difficulty: AiDifficulty.master,
    trees: 15,
    fog: true,
    diplomacy: true,
  ),
];

const playerScenarios = <PlayerScenario>[
  PlayerScenario(
    name: 'Swiss Cheese Royale',
    author: 'Steve Matssen',
    mapSize: MapSize.medium,
    players: 5,
    seed: 91001,
    difficulty: AiDifficulty.hard,
    trees: 10,
    diplomacy: true,
  ),
  PlayerScenario(
    name: 'Argentina 1816',
    author: 'nazapg23',
    mapSize: MapSize.medium,
    players: 6,
    seed: 94572,
    difficulty: AiDifficulty.hard,
    trees: 20,
    historical: true,
    fog: true,
  ),
  PlayerScenario(
    name: 'Hill Rush',
    author: 'Noldor',
    mapSize: MapSize.small,
    players: 4,
    seed: 98143,
    difficulty: AiDifficulty.hard,
    trees: 5,
  ),
  PlayerScenario(
    name: 'South East Asia',
    author: 'K. Sonmez',
    mapSize: MapSize.large,
    players: 7,
    seed: 101714,
    difficulty: AiDifficulty.veryHard,
    trees: 20,
    historical: true,
    diplomacy: true,
  ),
  PlayerScenario(
    name: '5 islands',
    author: 'Hankusha',
    mapSize: MapSize.medium,
    players: 5,
    humans: 2,
    seed: 105285,
    difficulty: AiDifficulty.hard,
    trees: 20,
    multiplayer: true,
    fog: true,
  ),
  PlayerScenario(
    name: 'Middle Earth (Evil)',
    author: 'S. Morris',
    mapSize: MapSize.large,
    players: 8,
    seed: 108856,
    difficulty: AiDifficulty.veryHard,
    trees: 25,
    diplomacy: true,
    fog: true,
  ),
  PlayerScenario(
    name: 'Middle Earth (Good)',
    author: 'S. Morris',
    mapSize: MapSize.large,
    players: 8,
    humans: 2,
    seed: 112427,
    difficulty: AiDifficulty.veryHard,
    trees: 25,
    multiplayer: true,
    diplomacy: true,
  ),
  PlayerScenario(
    name: 'Caspian Shores',
    author: 'Antiyoy Self',
    mapSize: MapSize.medium,
    players: 6,
    seed: 128981,
    difficulty: AiDifficulty.hard,
    trees: 10,
    historical: true,
  ),
  PlayerScenario(
    name: 'Blind Archipelago',
    author: 'Antiyoy Self',
    mapSize: MapSize.large,
    players: 9,
    seed: 143519,
    difficulty: AiDifficulty.master,
    trees: 20,
    fog: true,
  ),
  PlayerScenario(
    name: 'Council of Twelve',
    author: 'Antiyoy Self',
    mapSize: MapSize.huge,
    players: 12,
    seed: 157927,
    difficulty: AiDifficulty.master,
    trees: 15,
    diplomacy: true,
  ),
  PlayerScenario(
    name: 'Slay Mosaic',
    author: 'Antiyoy Self',
    mapSize: MapSize.large,
    players: 10,
    seed: 172399,
    difficulty: AiDifficulty.veryHard,
    trees: 5,
    slay: true,
  ),
  PlayerScenario(
    name: 'Local Alliance',
    author: 'Antiyoy Self',
    mapSize: MapSize.large,
    players: 8,
    humans: 4,
    seed: 186877,
    difficulty: AiDifficulty.hard,
    trees: 15,
    multiplayer: true,
    diplomacy: true,
    fog: true,
  ),
];
