"""Compile the reviewed KK | RU | EN catalogue into const Dart data."""
import json
from pathlib import Path

root = Path('lib/src/l10n')
rows = {}
for n, line in enumerate((root / 'catalog.txt').read_text(encoding='utf-8').splitlines(), 1):
    if not line or line.startswith('#'):
        continue
    parts = [part.replace(r'\n', '\n') for part in line.split('|')]
    if len(parts) != 3 or not all(parts):
        raise ValueError(f'Invalid translation at line {n}')
    if parts[0] in rows:
        raise ValueError(f'Duplicate translation at line {n}: {parts[0]}')
    rows[parts[0]] = parts[1:]

def quote(value):
    return json.dumps(value, ensure_ascii=False).replace('$', r'\$')

lines = ['// Generated by tool/build_translations.py. Edit catalog.txt instead.',
         'const gameTranslations = <String, List<String>>{']
for source, translations in rows.items():
    lines.append('  ' + quote(source) + ': [' + ', '.join(map(quote, translations)) + '],')
lines.append('};\n')
(root / 'catalog.dart').write_text('\n'.join(lines), encoding='utf-8')
print(f'{len(rows)} translations compiled')
